"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Contractor={id:string;company_name:string;contact_name?:string;email:string;countries?:string;services?:string;rating?:number};
type Dispatch={id:string;status:string;brief:string;response_deadline?:string;quote_amount?:number;currency?:string;availability?:string;personnel?:string;transport?:string;response_notes?:string;created_at:string;contractors?:Contractor};
export default function ContractorDispatch({reference,accessKey,service,country,location,requiredDate,people,urgency}:{reference:string;accessKey:string;service:string;country:string;location:string;requiredDate?:string;people?:string;urgency:string}){
 const [contractors,setContractors]=useState<Contractor[]>([]),[dispatches,setDispatches]=useState<Dispatch[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[selectedContractor,setSelectedContractor]=useState("");
 const uniqueContractors=useMemo(()=>{const seen=new Set<string>();return contractors.filter(c=>{const email=c.email.trim().toLowerCase();if(!email||seen.has(email))return false;seen.add(email);return true})},[contractors]);
 async function load(preselectId?:string){const r=await fetch(`/api/operations-dashboard/contractors?reference=${encodeURIComponent(reference)}`,{headers:{"x-operations-key":accessKey},cache:"no-store"});const j=await r.json();if(r.ok){setContractors(j.contractors||[]);setDispatches(j.dispatches||[]);if(preselectId)setSelectedContractor(preselectId)}else setMessage(j.message||"Unable to load contractors.")}
 useEffect(()=>{load()},[reference,accessKey]);
 async function addContractor(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());const r=await fetch("/api/operations-dashboard/contractors",{method:"POST",headers:{"Content-Type":"application/json","x-operations-key":accessKey},body:JSON.stringify({action:"addContractor",...data})});const j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.message||"Unable to add contractor.");form.reset();setMessage(j.message||(j.alreadyExists?"Contractor already exists and has been selected.":"Contractor added successfully."));await load(j.contractor?.id)}
 async function dispatch(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/operations-dashboard/contractors",{method:"POST",headers:{"Content-Type":"application/json","x-operations-key":accessKey},body:JSON.stringify({action:"dispatch",reference,...data,contractorId:selectedContractor})});const j=await r.json();setBusy(false);setMessage(j.warning||j.message||(r.ok?"Request sent to contractor.":"Unable to send request."));if(r.ok){setSelectedContractor("");e.currentTarget.reset();load()}}
 const defaultBrief=`Service: ${service}\nLocation: ${location}, ${country}\nRequired date: ${requiredDate||"To be confirmed"}\nPersonnel: ${people||"To be confirmed"}\nUrgency: ${urgency}\n\nPlease confirm availability, proposed team, transport and quotation.`;
 return <section className="contractorDispatch"><div className="contractorHeader"><div><p className="eyebrow">External partners</p><h3>Contractor Dispatch</h3><p>Send a restricted operational brief and compare contractor responses.</p></div><strong>{dispatches.length} dispatches</strong></div>
 <div className="contractorGrid"><form onSubmit={dispatch}><h4>Send request</h4><label><span>Contractor</span><select name="contractorId" required value={selectedContractor} onChange={e=>setSelectedContractor(e.target.value)}><option value="">Select contractor</option>{uniqueContractors.map(c=><option value={c.id} key={c.email.toLowerCase()}>{c.company_name} — {c.email}</option>)}</select></label><label><span>Response deadline</span><input type="datetime-local" name="responseDeadline"/></label><label><span>Restricted brief</span><textarea name="brief" rows={9} defaultValue={defaultBrief} required/></label><button className="button primary" disabled={busy}>Send to contractor</button></form>
 <form onSubmit={addContractor}><h4>Add contractor</h4><label><span>Company</span><input name="companyName" required/></label><label><span>Contact name</span><input name="contactName"/></label><label><span>Email</span><input name="email" type="email" required/></label><label><span>Phone</span><input name="phone"/></label><label><span>Countries / cities</span><input name="countries"/></label><label><span>Services</span><textarea name="services" rows={3}/></label><label><span>Rating 1–5</span><input name="rating" type="number" min="1" max="5"/></label><button className="button secondary" disabled={busy}>Add contractor</button></form></div>
 <div className="dispatchTable">{dispatches.map(d=><article key={d.id}><div><strong>{d.contractors?.company_name||"Contractor"}</strong><span>{d.status}</span></div><small>{new Date(d.created_at).toLocaleString("en-GB")}</small><p>{d.availability||"No response yet"}</p><b>{d.quote_amount?`${d.quote_amount} ${d.currency||""}`:"—"}</b>{d.response_notes&&<em>{d.response_notes}</em>}</article>)}{!dispatches.length&&<p className="documentsEmpty">No contractor requests have been sent.</p>}</div>{message&&<p className={message.includes("success")||message.includes("selected")||message.includes("sent")?"formMessage success":"formMessage error"}>{message}</p>}</section>
}
