"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Contractor={id:string;company_name:string;contact_name?:string;email:string;phone?:string;countries?:string;services?:string;rating?:number;notes?:string;status:string};
type Dispatch={id:string;reference?:string;contractor_id?:string;status:string;brief?:string;response_deadline?:string;quote_amount?:number;currency?:string;availability?:string;personnel?:string;transport?:string;response_notes?:string;created_at:string;viewed_at?:string;responded_at?:string;contractors?:Contractor};
export default function ContractorDispatch({reference,accessKey,service,country,location,requiredDate,people,urgency}:{reference:string;accessKey:string;service:string;country:string;location:string;requiredDate?:string;people?:string;urgency:string}){
 const [contractors,setContractors]=useState<Contractor[]>([]),[dispatches,setDispatches]=useState<Dispatch[]>([]),[history,setHistory]=useState<Dispatch[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [selectedId,setSelectedId]=useState(""),[profileId,setProfileId]=useState(""),[query,setQuery]=useState(""),[countryFilter,setCountryFilter]=useState("All"),[serviceFilter,setServiceFilter]=useState("All"),[showInactive,setShowInactive]=useState(false);
 async function load(){const r=await fetch(`/api/operations-dashboard/contractors?reference=${encodeURIComponent(reference)}`,{headers:{"x-operations-key":accessKey},cache:"no-store"});const j=await r.json();if(r.ok){setContractors(j.contractors||[]);setDispatches(j.dispatches||[]);setHistory(j.contractorHistory||[])}else setMessage(j.message||"Unable to load contractors.")}
 useEffect(()=>{load()},[reference,accessKey]);
 async function send(data:Record<string,unknown>){setBusy(true);setMessage("");const r=await fetch("/api/operations-dashboard/contractors",{method:"POST",headers:{"Content-Type":"application/json","x-operations-key":accessKey},body:JSON.stringify(data)});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.message||"Unable to save changes.");return null}setMessage(j.message||"Saved successfully.");await load();return j}
 async function addContractor(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const j=await send({action:"addContractor",...Object.fromEntries(new FormData(form).entries())});if(j){form.reset();setSelectedId(j.contractor?.id||"");setProfileId(j.contractor?.id||"")}}
 async function updateContractor(e:FormEvent<HTMLFormElement>){e.preventDefault();await send({action:"updateContractor",id:profileId,...Object.fromEntries(new FormData(e.currentTarget).entries())})}
 async function dispatch(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const j=await send({action:"dispatch",reference,...Object.fromEntries(new FormData(form).entries())});if(j){form.reset();setSelectedId("")}}
 async function setStatus(id:string,status:"Active"|"Inactive"){await send({action:"setContractorStatus",id,status});if(status==="Inactive"&&profileId===id)setProfileId("")}
 const countries=useMemo(()=>Array.from(new Set(contractors.flatMap(c=>(c.countries||"").split(",").map(x=>x.trim()).filter(Boolean)))).sort(),[contractors]);
 const services=useMemo(()=>Array.from(new Set(contractors.flatMap(c=>(c.services||"").split(",").map(x=>x.trim()).filter(Boolean)))).sort(),[contractors]);
 const visible=useMemo(()=>contractors.filter(c=>(showInactive||c.status!=="Inactive")&&(countryFilter==="All"||(c.countries||"").toLowerCase().includes(countryFilter.toLowerCase()))&&(serviceFilter==="All"||(c.services||"").toLowerCase().includes(serviceFilter.toLowerCase()))&&`${c.company_name} ${c.contact_name||""} ${c.email} ${c.countries||""} ${c.services||""}`.toLowerCase().includes(query.toLowerCase())),[contractors,query,countryFilter,serviceFilter,showInactive]);
 const profile=contractors.find(c=>c.id===profileId)||null;
 const profileHistory=history.filter(d=>d.contractor_id===profileId);
 const responded=profileHistory.filter(d=>["Accepted","Declined","Clarification"].includes(d.status));
 const accepted=profileHistory.filter(d=>d.status==="Accepted").length;
 const responseTimes=responded.filter(d=>d.responded_at).map(d=>(new Date(d.responded_at!).getTime()-new Date(d.created_at).getTime())/3600000).filter(n=>n>=0);
 const avgResponse=responseTimes.length?Math.round(responseTimes.reduce((a,b)=>a+b,0)/responseTimes.length*10)/10:null;
 const defaultBrief=`Service: ${service}\nLocation: ${location}, ${country}\nRequired date: ${requiredDate||"To be confirmed"}\nPersonnel: ${people||"To be confirmed"}\nUrgency: ${urgency}\n\nPlease confirm availability, proposed team, transport and quotation.`;
 return <section className="contractorDispatch"><div className="contractorHeader"><div><p className="eyebrow">External partners</p><h3>Contractor Dispatch</h3><p>Manage partner profiles, send restricted briefs and compare performance.</p></div><strong>{contractors.filter(c=>c.status!=="Inactive").length} active</strong></div>
 <div className="contractorDirectory"><div className="contractorFilters"><input placeholder="Search company, contact, country or service" value={query} onChange={e=>setQuery(e.target.value)}/><select value={countryFilter} onChange={e=>setCountryFilter(e.target.value)}><option>All</option>{countries.map(x=><option key={x}>{x}</option>)}</select><select value={serviceFilter} onChange={e=>setServiceFilter(e.target.value)}><option>All</option>{services.map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/> Show inactive</label></div><div className="contractorCards">{visible.map(c=>{const records=history.filter(d=>d.contractor_id===c.id),acceptedCount=records.filter(d=>d.status==="Accepted").length;return <button type="button" className={profileId===c.id?"active":""} key={c.id} onClick={()=>setProfileId(c.id)}><div><strong>{c.company_name}</strong><span>{c.contact_name||c.email}</span></div><small>{c.countries||"No coverage listed"}</small><b>{c.rating?`${"★".repeat(Math.round(c.rating))} `:""}{records.length} requests · {records.length?Math.round(acceptedCount/records.length*100):0}% accepted</b>{c.status==="Inactive"&&<em>Inactive</em>}</button>})}{!visible.length&&<p className="documentsEmpty">No contractors match the filters.</p>}</div></div>
 <div className="contractorGrid"><form onSubmit={dispatch}><h4>Send request</h4><label><span>Contractor</span><select name="contractorId" required value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select contractor</option>{contractors.filter(c=>c.status!=="Inactive").map(c=><option value={c.id} key={c.id}>{c.company_name} — {c.email}</option>)}</select></label><label><span>Response deadline</span><input type="datetime-local" name="responseDeadline"/></label><label><span>Restricted brief</span><textarea name="brief" rows={9} defaultValue={defaultBrief} required/></label><button className="button primary" disabled={busy}>Send to contractor</button></form>
 <form onSubmit={addContractor}><h4>Add contractor</h4><label><span>Company</span><input name="companyName" required/></label><label><span>Contact name</span><input name="contactName"/></label><label><span>Email</span><input name="email" type="email" required/></label><label><span>Phone</span><input name="phone"/></label><label><span>Countries / cities</span><input name="countries" placeholder="Nigeria, Ghana, Lagos"/></label><label><span>Services</span><textarea name="services" rows={3} placeholder="Executive protection, secure transport"/></label><label><span>Rating 1–5</span><input name="rating" type="number" min="1" max="5"/></label><button className="button secondary" disabled={busy}>Add contractor</button></form></div>
 {profile&&<section className="contractorProfile"><div className="contractorProfileHead"><div><p className="eyebrow">Partner profile</p><h4>{profile.company_name}</h4><p>{profile.email}{profile.phone?` · ${profile.phone}`:""}</p></div><div><button type="button" onClick={()=>setSelectedId(profile.id)}>Use for this request</button><button type="button" onClick={()=>setStatus(profile.id,profile.status==="Inactive"?"Active":"Inactive")}>{profile.status==="Inactive"?"Reactivate":"Archive"}</button></div></div><div className="contractorMetrics"><article><span>Total requests</span><strong>{profileHistory.length}</strong></article><article><span>Responses</span><strong>{responded.length}</strong></article><article><span>Acceptance rate</span><strong>{profileHistory.length?Math.round(accepted/profileHistory.length*100):0}%</strong></article><article><span>Average response</span><strong>{avgResponse===null?"—":`${avgResponse}h`}</strong></article></div><form onSubmit={updateContractor} key={profile.id} className="contractorEdit"><label><span>Company</span><input name="companyName" defaultValue={profile.company_name} required/></label><label><span>Contact name</span><input name="contactName" defaultValue={profile.contact_name||""}/></label><label><span>Email</span><input name="email" type="email" defaultValue={profile.email} required/></label><label><span>Phone</span><input name="phone" defaultValue={profile.phone||""}/></label><label><span>Countries / cities</span><input name="countries" defaultValue={profile.countries||""}/></label><label><span>Services</span><input name="services" defaultValue={profile.services||""}/></label><label><span>Rating 1–5</span><input name="rating" type="number" min="1" max="5" defaultValue={profile.rating||""}/></label><label className="contractorNotes"><span>Internal notes</span><textarea name="notes" rows={3} defaultValue={profile.notes||""}/></label><button className="button secondary" disabled={busy}>Save contractor profile</button></form><div className="contractorHistory"><h5>Request history</h5>{profileHistory.slice(0,12).map(d=><article key={d.id}><strong>{d.reference}</strong><span>{d.status}</span><small>{new Date(d.created_at).toLocaleString("en-GB")}</small><b>{d.quote_amount?`${d.quote_amount} ${d.currency||""}`:"—"}</b></article>)}{!profileHistory.length&&<p className="documentsEmpty">No requests have been sent to this contractor.</p>}</div></section>}
 <div className="dispatchTable">{dispatches.map(d=><article key={d.id}><div><strong>{d.contractors?.company_name||"Contractor"}</strong><span>{d.status}</span></div><small>{new Date(d.created_at).toLocaleString("en-GB")}</small><p>{d.availability||"No response yet"}</p><b>{d.quote_amount?`${d.quote_amount} ${d.currency||""}`:"—"}</b>{d.response_notes&&<em>{d.response_notes}</em>}</article>)}{!dispatches.length&&<p className="documentsEmpty">No contractor requests have been sent.</p>}</div>{message&&<p className={message.includes("success")||message.includes("sent")||message.includes("exists")?"formMessage success":"formMessage error"}>{message}</p>}</section>
}
