import type { Metadata } from "next";

export const metadata: Metadata = { title: "Executive Protection Planning Checklist", description: "A practical checklist for preparing executive protection and secure mobility requirements in Nigeria and West Africa." };

const checklist=["Traveller names and roles","Complete itinerary and movement windows","Airport, hotel, office and venue addresses","Known public exposure or media profile","Host and event contacts","Vehicle and luggage requirements","Medical or accessibility needs on a need-to-know basis","Communication and escalation contacts","Privacy and confidentiality restrictions","Last-minute change approval process"];

export default function ExecutiveProtectionChecklist(){return <main>
<header className="siteHeader enterpriseHeader"><a className="brand" href="/"><img src="/logo.svg" alt="Africa Security Solutions" /></a><nav><a href="/services">Services</a><a href="/locations">Locations</a><a href="/resources">Resources</a><a href="/standards">Standards</a><a href="/contact">Contact</a><a className="navCta" href="/contact">Request Consultation</a></nav></header>
<section className="enterpriseHero guideHero"><div className="serviceHeroOverlay"/><div className="serviceHeroContent"><nav className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/resources">Resources</a><span>›</span><span>Executive Protection</span></nav><p className="eyebrow">Planning checklist</p><h1>Preparing an executive protection assignment.</h1><p className="lead">The information required to assess protective coverage, secure mobility, privacy needs and operational complexity before deployment.</p></div></section>
<article className="guideContent"><p className="guideDisclaimer">General planning guidance only. Final recommendations depend on current conditions, lawful availability, traveller profile and an operational assessment.</p><h2>1. Define the purpose and exposure</h2><p>Explain why the principal is travelling, where public visibility may occur, who will know the programme and whether media, protests, sensitive negotiations or high-value activity are relevant.</p><h2>2. Provide the complete movement picture</h2><p>Include airports, hotels, offices, private residences, event venues, meeting windows, expected delays and all people moving with the principal.</p><h2>3. Confirm the protection style</h2><p>State whether the requirement is discreet low-profile support, visible deterrence, close protection, secure driving or a combination of services.</p><h2>4. Establish communication authority</h2><p>Nominate one client decision-maker for itinerary changes, approvals and escalation. This reduces confusion during time-sensitive movements.</p><h2>5. Protect sensitive information</h2><p>Limit access to itineraries, personal details and accommodation information. Share only what is necessary for planning and delivery.</p><h2>Assignment checklist</h2><div className="enterpriseList guideList">{checklist.map(item=><span key={item}>{item}</span>)}</div><div className="guideCta"><h2>Need a protective planning review?</h2><p>Send the dates, locations, traveller profile and itinerary for an initial assessment.</p><a className="button primary" href="/contact">Request a review</a></div></article>
</main>}
