import type { Metadata } from "next";

export const metadata: Metadata = { title: "Journey Planning and Movement Management Guide", description: "A practical journey management framework for route assessment, communications and contingency planning in Nigeria and West Africa." };

const checklist=["Origin, destination and required arrival time","Primary and alternative routes","Traveller, driver and vehicle details","Fuel and rest planning","Scheduled check-in points","Known route restrictions","Medical and breakdown contingencies","Weather and disruption review","Escalation contacts","Arrival confirmation procedure"];

export default function JourneyPlanningGuide(){return <main>
<header className="siteHeader enterpriseHeader"><a className="brand" href="/"><img src="/logo.svg" alt="Africa Security Solutions" /></a><nav><a href="/services">Services</a><a href="/locations">Locations</a><a href="/resources">Resources</a><a href="/standards">Standards</a><a href="/contact">Contact</a><a className="navCta" href="/contact">Request Consultation</a></nav></header>
<section className="enterpriseHero guideHero"><div className="serviceHeroOverlay"/><div className="serviceHeroContent"><nav className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/resources">Resources</a><span>›</span><span>Journey Planning</span></nav><p className="eyebrow">Movement framework</p><h1>Planning controlled road movements.</h1><p className="lead">A structured approach to route selection, communications, check-ins, alternatives and escalation before a vehicle departs.</p></div></section>
<article className="guideContent"><p className="guideDisclaimer">General guidance only. Route suitability and risk conditions can change quickly. Obtain a current operational review for each movement.</p><h2>1. Define the movement objective</h2><p>Record the origin, destination, required arrival time, passenger profile, vehicle needs and whether stops or multiple pickups are expected.</p><h2>2. Review route options</h2><p>Assess the primary route and realistic alternatives, including road conditions, timing, fuel availability, communications coverage and known restrictions.</p><h2>3. Set check-in points</h2><p>Agree when the movement will report departure, progress, delays, route changes and safe arrival. Define who monitors those updates.</p><h2>4. Establish escalation triggers</h2><p>Decide what should happen after a missed check-in, breakdown, medical issue, severe delay, road closure or unexpected security concern.</p><h2>5. Close the movement formally</h2><p>Confirm safe arrival, record significant delays or incidents and capture lessons that should inform future movements.</p><h2>Journey checklist</h2><div className="enterpriseList guideList">{checklist.map(item=><span key={item}>{item}</span>)}</div><div className="guideCta"><h2>Need a journey management plan?</h2><p>Send the route, date, passenger count, vehicle requirement and expected schedule.</p><a className="button primary" href="/contact">Request journey planning</a></div></article>
</main>}
