import type { Metadata } from "next";

export const metadata: Metadata = { title: "Airport Arrival Security Guide", description: "A practical airport arrival and secure transfer planning guide for executives, crews and corporate travellers in Nigeria." };

const checklist=["Flight number, terminal and estimated arrival time","Traveller and crew contact details","Verified pickup representative","Vehicle description and registration","Agreed meeting point","Hotel or onward destination","Luggage and equipment requirements","Delay and diversion procedure","Communication check after landing","Escalation contact for missed connection"];

export default function AirportArrivalGuide(){return <main>
<header className="siteHeader enterpriseHeader"><a className="brand" href="/"><img src="/logo.svg" alt="Africa Security Solutions" /></a><nav><a href="/services">Services</a><a href="/locations">Locations</a><a href="/resources">Resources</a><a href="/standards">Standards</a><a href="/contact">Contact</a><a className="navCta" href="/contact">Request Consultation</a></nav></header>
<section className="enterpriseHero guideHero"><div className="serviceHeroOverlay"/><div className="serviceHeroContent"><nav className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/resources">Resources</a><span>›</span><span>Airport Arrival</span></nav><p className="eyebrow">Arrival guide</p><h1>Planning a controlled airport arrival.</h1><p className="lead">A practical framework for meet-and-assist coordination, traveller verification, secure transfers and disruption management.</p></div></section>
<article className="guideContent"><p className="guideDisclaimer">General guidance only. Airport procedures, access permissions and operating conditions may change. Confirm current arrangements before travel.</p><h2>1. Confirm the exact arrival details</h2><p>Share the airline, flight number, terminal, scheduled arrival, passenger count and any special handling requirements. Update the operations contact when schedules change.</p><h2>2. Use a verification process</h2><p>Travellers should know the representative’s name, phone number, meeting location and vehicle details. Last-minute substitutions should be verified through an agreed contact.</p><h2>3. Plan the handover point</h2><p>Clarify where responsibility begins: aircraft-side where lawfully permitted, arrivals hall, terminal exit or a prearranged vehicle pickup zone.</p><h2>4. Account for delays and baggage</h2><p>Include a procedure for delayed flights, missing baggage, terminal changes, diversions and travellers arriving separately.</p><h2>5. Coordinate the onward movement</h2><p>Confirm the hotel or destination, preferred route, alternative route, expected journey time and communication checks during transit.</p><h2>Arrival checklist</h2><div className="enterpriseList guideList">{checklist.map(item=><span key={item}>{item}</span>)}</div><div className="guideCta"><h2>Planning an airport or crew movement?</h2><p>Send the flight details, passenger count, destination and required support for an initial review.</p><a className="button primary" href="/contact">Request airport support</a></div></article>
</main>}
