import type { Metadata } from "next";

export const metadata: Metadata = { title: "Nigeria Travel Security Planning Guide", description: "A practical pre-travel security planning framework for executive and corporate movements in Nigeria." };

const checklist=["Confirmed itinerary and traveller contacts","Airport, hotel and meeting addresses","Local host and emergency contacts","Approved ground transport plan","Primary and alternative routes","Scheduled movement check-ins","Medical information shared on a need-to-know basis","Escalation and communication protocol"];

export default function TravelSecurityGuide(){return <main>
<header className="siteHeader enterpriseHeader"><a className="brand" href="/"><img src="/logo.svg" alt="Africa Security Solutions" /></a><nav><a href="/services">Services</a><a href="/locations">Locations</a><a href="/resources">Resources</a><a href="/standards">Standards</a><a href="/contact">Contact</a><a className="navCta" href="/contact">Request Consultation</a></nav></header>
<section className="enterpriseHero guideHero"><div className="serviceHeroOverlay"/><div className="serviceHeroContent"><nav className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/resources">Resources</a><span>›</span><span>Travel Security</span></nav><p className="eyebrow">Planning guide</p><h1>Preparing corporate travel to Nigeria.</h1><p className="lead">A practical framework for organising itinerary information, secure mobility, communications and contingency planning before departure.</p></div></section>
<article className="guideContent"><p className="guideDisclaimer">General guidance only. Conditions and requirements vary by location, traveller profile and date. Obtain current professional advice before travel.</p><h2>1. Build one verified itinerary</h2><p>Keep flight details, accommodation, meetings, addresses, hosts and traveller contacts in one controlled document. Changes should be communicated through an agreed point of contact.</p><h2>2. Plan transport before arrival</h2><p>Confirm who will meet the traveller, vehicle details, driver identification, pickup location, route expectations and a method for verifying last-minute changes.</p><h2>3. Define communication checks</h2><p>Agree when travellers or drivers will check in, who receives those updates and what happens when a scheduled communication is missed.</p><h2>4. Prepare alternatives</h2><p>Identify alternative routes, meeting options, accommodation and movement windows where disruption could affect the original programme.</p><h2>5. Limit sensitive information</h2><p>Share personal, medical and itinerary information only with people who genuinely require it for planning or service delivery.</p><h2>Pre-travel checklist</h2><div className="enterpriseList guideList">{checklist.map(item=><span key={item}>{item}</span>)}</div><div className="guideCta"><h2>Need a location-specific assessment?</h2><p>Send the cities, dates, traveller profile and schedule for an initial operational review.</p><a className="button primary" href="/contact">Request an assessment</a></div></article>
</main>}
